apiVersion: v1
kind: Service
metadata:
  name: i4q-demo-webapp-service
  namespace: i4q-demo
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 5000
  selector:
    app: i4q-demo-webapp
  type: LoadBalancer