apiVersion: v1
kind: Service
metadata:
  name: i4q-demo-restapi-service
  namespace: i4q-demo
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 6000
  selector:
    app: i4q-demo-restapi
  type: ClusterIP